uploads = []
outputs = []

[[generated]]
id = "rOPNeI8LuHUOhrvomuy6U"
uri = "file://artifacts/elfor-store/public/categories/ulichnoe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ioQW9M1Y0w4tv9HoX5sV2"
uri = "file://artifacts/elfor-store/public/categories/parkovoe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zYi9mDuycqccDoBVYSoJB"
uri = "file://artifacts/elfor-store/public/categories/promyshlennye-ufo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2CD6kiD8VG49e_KWE2TBd"
uri = "file://artifacts/elfor-store/public/categories/promyshlennye-modulnye.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ILS5uua2zeDU9VAuSu1Qj"
uri = "file://artifacts/elfor-store/public/categories/lineynye.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xiiLA-kOtNhHsd6IOJxVh"
uri = "file://artifacts/elfor-store/public/categories/prozhektory.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qS4kd6eyQpDPjH6ariATs"
uri = "file://artifacts/elfor-store/public/categories/podvesnye-panelnye.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Od6EI0D1bRTem7Wamg-Gl"
uri = "file://artifacts/elfor-store/public/categories/svlenta.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5x7Z44_tzsx21gDbSD9JT"
uri = "file://artifacts/elfor-store/public/products/L4U10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3j5plg0h_IzhRsEmIF8k7"
uri = "file://artifacts/elfor-store/public/products/L4U15.png"
type = "image"
title = "generated_image"

[[generated]]
id = "w5zhEDvShQOGXcmup1Do9"
uri = "file://artifacts/elfor-store/public/products/L4P10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "K6z1wThNhRgOYeicQXKOR"
uri = "file://artifacts/elfor-store/public/products/L4KA10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Abqfqnchnh0n-hnaX1kdI"
uri = "file://artifacts/elfor-store/public/products/L4F10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "y5g_Hj8q440kpct_mcPwS"
uri = "file://artifacts/elfor-store/public/products/L4S10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NJJSs9kvgJGRpdMD7rDeE"
uri = "file://artifacts/elfor-store/public/products/L4MF12.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wxa0LYe9IKKDZBv3WY4jL"
uri = "file://artifacts/elfor-store/public/products/L4P06.png"
type = "image"
title = "generated_image"
