// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/elfor-homepage/VariantA.tsx": () => import("../components/mockups/elfor-homepage/VariantA.tsx"),
  "./components/mockups/elfor-homepage/VariantB.tsx": () => import("../components/mockups/elfor-homepage/VariantB.tsx")
};
