// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/elfor-homepage/VariantA.tsx": () => import("../components/mockups/elfor-homepage/VariantA.tsx"),
  "./components/mockups/elfor-homepage/VariantB.tsx": () => import("../components/mockups/elfor-homepage/VariantB.tsx"),
  "./components/mockups/email-preview/ElforCalcEmail.tsx": () => import("../components/mockups/email-preview/ElforCalcEmail.tsx"),
  "./components/mockups/calc-banner/VariantA.tsx": () => import("../components/mockups/calc-banner/VariantA.tsx"),
  "./components/mockups/calc-banner/VariantB.tsx": () => import("../components/mockups/calc-banner/VariantB.tsx"),
  "./components/mockups/calc-banner/VariantC.tsx": () => import("../components/mockups/calc-banner/VariantC.tsx")
};
